name: .NET 8 CI

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: s

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet-format tool
      run: dotnet tool install -g dotnet-format

    - name: Enable long paths
      run: New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
      shell: powershell

    - name: Clean old build artifacts
      run: |
        dotnet clean s\BackApi.sln
        Remove-Item -Recurse -Force .\**\bin
        Remove-Item -Recurse -Force .\**\obj
      shell: powershell

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Restore NuGet packages
      run: dotnet restore s\BackApi.sln --force --no-cache

    - name: Build project
      run: dotnet build s\BackApi.sln --configuration Release

    - name: Verify code formatting
      run: dotnet format --verify-no-changes --no-restore
